### ISSUE TITLE
Seems not to work as npm script

### ISSUE THREAD

**Issue by tomekwi** [shama/testron#2]
Hi!

This is a fabulous module I’ve long been waiting for! It works wonderfully when I use it directly from the command line:

```sh
$ browserify -t babelify test.js | testron
# or with the local binaries:
$ node_modules/.bin/browserify -t ./node_modules/babelify test.js | node_modules/.bin/testron
```

But the same command run from an npm script fails – `test.js` isn’t executed.

You can see the results of an `npm test` [on Travis](https://travis-ci.org/parametric-svg/html/builds/80861821) or do a `git clone git@github.com:parametric-svg/element; git checkout 9d152fb; npm i; npm t` locally – I get the same results on both boxes.

I managed to work around this by delegating the test to [a shell script](https://github.com/parametric-svg/element/commit/e934919cd1c90fa52a79ee4964c7ef3a7cd1397c) run [without](https://github.com/parametric-svg/element/commit/c6616847b08211486f126f50dae40785a59fd56a) the npm machinery. Running the shell script [through npm](https://github.com/parametric-svg/element/commit/736b8a52222c52e57418b8f9ae35baa191e1cc86) failed just like the raw `npm test` solution.

**Comment by tomekwi** [comment]
Hmm, it looks like it’s not npm but node who screws things up.

When I run

<pre>
$ <a href="http://npm.im/nodangel">nodangel</a> --ignore node_modules --exec './test.sh'
</pre>

…the thing fails exactly the same way.

**Comment by tomekwi** [comment]
I think I managed to isolate the problem somehow:

<pre>
$ browserify --transform=babelify test.js | <b>testron</b> | tap-spec

  Registers the <parametric-svg> element

    ✓ taking a custom implementation of `document`
    ✓ under the name <parametric-svg>
    ✓ as a standard HTML element – no bells and whistles
    ✓ attaching stuff to the createdCallback…
    ✓ …and to no other lifecycle callback
   
  total:     5
  passing:   5
  duration:  1.7s

  All tests pass!
</pre>

<pre>
$ browserify --transform=babelify test.js | <b>node_modules/.bin/testron</b> | tap-spec
  total:     0
  passing:   0
  duration:  1.4s

  Failed: No assertions found.
</pre>

That’s really funny because both the global and the local install of *testron* are at v1.2.0.

**Comment by tomekwi** [comment]
I tried the above commands at https://github.com/parametric-svg/element/commit/26acc02353ad60781b03061d3d70484b26f9a409 – in case you try to reproduce them.

I’m running *node* v4.0.0 and *npm* v2.14.2 on a Fedora 22 x64 box.

**Comment by tomekwi** [comment]
I took another shot at the config today – still getting the same results. I now have more details to share though.

Testron command               | Version of electron   | Works
---------------               | -------------------   | -----
`node_modules/.bin/testron`   | 0.33 (local)          | ✘
`testron`                     | 0.33 (global)         | ✘
`node_modules/.bin/testron`   | 0.32 (local)          | ✘
`testron`                     | 0.32 (global)         | ✔

BTW, I’ve posting the output piped through *[tap-spec](http://npm.im/tap-spec)* because it’s more readable. I can post the raw output if you want. But the passing TAP output is quite predictable. The failing output is simply empty.

**Comment by tomekwi** [comment]
Those are the results on my box. Travis [happily takes](https://travis-ci.org/parametric-svg/element/builds/81138158) a [local](https://github.com/parametric-svg/element/blob/ff8d90f17cbf17ef78e65db265ae430b335af0e5/test.sh) version of both binaries with [electron@0.33](https://github.com/parametric-svg/element/blob/ff8d90f17cbf17ef78e65db265ae430b335af0e5/package.json#L62). I’m lost :)

**Comment by shama** [comment]
Very strange. I tried running that repo at https://github.com/parametric-svg/element/commit/26acc02353ad60781b03061d3d70484b26f9a409 but ran into a lot of missing deps so gave up.

Would you mind updating that repo with the missing deps or simplifying it while still able to reproduce the issue? So I can take a look? Thanks!

**Comment by tomekwi** [comment]
Hmm, the missing deps have puzzled me. I always do my best to keep my `package.json` up to date. I did a fresh clone on another box and I didn’t run into any dependency problems. [Neither does travis](https://travis-ci.org/parametric-svg/element/builds/80869776). 

But I can’t reproduce the problem here. I’m now in a bit of a hurry, but I’ll try to reproduce the problem on this other machine. Perhaps I’ll manage to put together a minimal example – but that might be hard – feels lika a hide and seek game :) .

**Comment by shama** [comment]
Oh sorry, never mind. I had a conflicting project named `element` already and the missing deps were in there!

Here is what I get after cloning that commit and running `npm i`...

```
$ ./test.sh 

  Registers the <parametric-svg> element

    ✓ taking a custom implementation of `document`
    ✓ under the name <parametric-svg>
    ✓ as a standard HTML element – no bells and whistles
    ✓ attaching stuff to the createdCallback…
    ✓ …and to no other lifecycle callback
   
   
   
  total:     5
  passing:   5
  duration:  3.2s

  All tests pass!
```

Then I modified the `"test"` script to:

`browserify --transform=babelify test.js | testron | tap-spec`
```
$ npm test

> parametric-svg-element@0.0.0-work-in-progress test /Users/Kyle/Documents/www/element
> browserify --transform=babelify test.js | testron | tap-spec


  Registers the <parametric-svg> element

    ✓ taking a custom implementation of `document`
    ✓ under the name <parametric-svg>
    ✓ as a standard HTML element – no bells and whistles
    ✓ attaching stuff to the createdCallback…
    ✓ …and to no other lifecycle callback
   
   
   
  total:     5
  passing:   5
  duration:  2.8s

  All tests pass!
```

**Comment by tomekwi** [comment]
I get exactly the same results on my work machine. It was my laptop [and travis](https://travis-ci.org/parametric-svg/element/builds/80861821) that produced these funny results.

I tried checking out https://github.com/parametric-svg/element/commit/9d152fb – the same the broken build points to – I have no problems on my work box:

```
> parametric-svg-element@0.0.0-work-in-progress test /home/tomekwi/Web/parametric-svg/element
> eslint . && npm run test:lite


> parametric-svg-element@0.0.0-work-in-progress test:lite /home/tomekwi/Web/parametric-svg/element
> browserify --transform=babelify test.js | testron | tap-spec


  Registers the <parametric-svg> element

    ✓ taking a custom implementation of `document`
    ✓ under the name <parametric-svg>
    ✓ as a standard HTML element – no bells and whistles
    ✓ attaching stuff to the createdCallback…
    ✓ …and to no other lifecycle callback
   
   
   
  total:     5
  passing:   5
  duration:  1.7s

  All tests pass!
```

**Comment by tomekwi** [comment]
All in all, this thing seems to be insanely difficult to reproduce. Feel free to ignore it for now. My current setup kind-a-works – enough for my use case at least. If I or someone else manage to find more details, you can reopen the issue.

Thanks for your help @shama!

BTW, the travis build I linked to isn’t the only build that failed – but the only one I left in the commit history. I did lots of trial-and-error stuff in a separate branch.

BTW2, the latter builds (for example, https://travis-ci.org/parametric-svg/element/builds/81351123) succeed on Travis but fail on my laptop.

BTW3, I have the exact same system and exact same version node and npm on my work box and laptop (Fedora 22 x64).

```
$ node --version; npm --version
v4.0.0
2.14.2
```

**Comment by tomekwi** [comment]
As for the test failing with a local install of *testron* – it looks like https://github.com/maxogden/electron-spawn/issues/13 was the cause. I had the project cloned at `…/Parametric SVG/…`. That’s why it didn’t work with a local *testron* and did with a global one.
